import { ProcessedEvent, HistoryPoint } from './types';

// Generate historical price data for the past 30 days
function generateHistory(basePrice: number, volatility: number): HistoryPoint[] {
  const history: HistoryPoint[] = [];
  const now = Date.now();
  const thirtyDaysAgo = now - 30 * 24 * 60 * 60 * 1000;

  let price = basePrice - volatility * 10 + Math.random() * volatility * 5;

  for (let ts = thirtyDaysAgo; ts <= now; ts += 24 * 60 * 60 * 1000) {
    // Random walk with mean reversion toward base price
    const drift = (basePrice - price) * 0.05;
    const noise = (Math.random() - 0.5) * volatility;
    price = Math.max(1, Math.min(99, price + drift + noise));

    history.push({
      timestamp: ts,
      price: Math.round(price),
    });
  }

  return history;
}

export const MOCK_MARKETS: ProcessedEvent[] = [
  {
    event_ticker: 'KXFEDRATE',
    market_ticker: 'KXFEDRATE-25JAN',
    event_title: 'Federal Reserve Interest Rate Decision',
    market_title: 'Fed holds rates steady in January 2025?',
    category: 'Economics',
    current_yes_price: 72,
    yes_bid: 71,
    yes_ask: 73,
    volume_24h: 45230,
    open_interest: 128500,
    close_time: '2025-01-29T19:00:00Z',
    expiration_time: '2025-01-30T00:00:00Z',
    historicals: generateHistory(72, 8),
    sentiment_score: 0.35,
    analysis: 'Based on recent Fed communications and economic data, the market expects rates to remain unchanged. Inflation has cooled but remains above target, suggesting a cautious approach.',
    predicted_outcome: 'YES',
    confidence: 78,
    summary: 'The Federal Reserve is widely expected to hold interest rates steady at their January meeting. Recent economic indicators show inflation cooling toward the 2% target while employment remains strong. Fed officials have signaled patience in their approach to rate cuts.',
    tldr: 'Fed likely to hold rates as inflation cools but remains above target.',
    key_takeaways: [
      'Inflation trending down but above 2% target',
      'Labor market remains resilient',
      'Fed officials signaling patience on cuts',
      'Markets pricing in rate cuts later in 2025',
    ],
    risks: [
      { description: 'Unexpected inflation spike could force rate hike', severity: 'MEDIUM', likelihood: 'LOW' },
      { description: 'Banking sector stress could accelerate cuts', severity: 'HIGH', likelihood: 'LOW' },
    ],
    sources: [
      { title: 'Federal Reserve Press Release', url: 'https://federalreserve.gov', relevance: 'Primary source for rate decisions' },
      { title: 'WSJ Fed Watch', url: 'https://wsj.com', relevance: 'Analysis of Fed policy trajectory' },
    ],
  },
  {
    event_ticker: 'KXBTC100K',
    market_ticker: 'KXBTC100K-25Q1',
    event_title: 'Bitcoin Price Milestones',
    market_title: 'Bitcoin reaches $100K by end of Q1 2025?',
    category: 'Crypto',
    current_yes_price: 45,
    yes_bid: 44,
    yes_ask: 46,
    volume_24h: 89450,
    open_interest: 342000,
    close_time: '2025-03-31T23:59:59Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(45, 15),
    sentiment_score: 0.15,
    analysis: 'Bitcoin sentiment remains mixed. While ETF inflows continue, macroeconomic uncertainty and regulatory concerns create headwinds. The $100K target requires significant momentum.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 52,
    summary: 'Bitcoin ETF approval has driven institutional adoption, but reaching $100K by Q1 2025 remains uncertain. Current price action shows consolidation, and macro factors including Fed policy will influence trajectory.',
    tldr: 'Bitcoin path to $100K faces headwinds despite ETF tailwinds.',
    key_takeaways: [
      'Spot ETF inflows providing steady demand',
      'Halving event in 2024 historically bullish',
      'Regulatory uncertainty persists globally',
      'Macro conditions mixed for risk assets',
    ],
    risks: [
      { description: 'Major exchange failure could crash prices', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Regulatory crackdown in major markets', severity: 'HIGH', likelihood: 'MEDIUM' },
      { description: 'Broader risk-off sentiment in markets', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'CoinDesk Market Analysis', url: 'https://coindesk.com', relevance: 'Crypto market coverage' },
      { title: 'Bloomberg Crypto', url: 'https://bloomberg.com', relevance: 'Institutional perspective' },
    ],
  },
  {
    event_ticker: 'KXNFLSB',
    market_ticker: 'KXNFLSB-CHIEFS',
    event_title: 'Super Bowl LIX Winner',
    market_title: 'Kansas City Chiefs win Super Bowl LIX?',
    category: 'Sports',
    current_yes_price: 28,
    yes_bid: 27,
    yes_ask: 29,
    volume_24h: 156780,
    open_interest: 892000,
    close_time: '2025-02-09T23:59:59Z',
    expiration_time: '2025-02-10T06:00:00Z',
    historicals: generateHistory(28, 6),
    sentiment_score: 0.22,
    analysis: 'The Chiefs remain contenders with Mahomes, but face stiff competition. Their odds reflect a realistic but not dominant chance at a three-peat.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 45,
    summary: 'Kansas City seeks an unprecedented three-peat with Patrick Mahomes leading the charge. While they remain favorites, the competitive AFC presents significant obstacles.',
    tldr: 'Chiefs three-peat bid faces tough AFC competition.',
    key_takeaways: [
      'Mahomes remains elite quarterback',
      'Offensive weapons healthy for playoffs',
      'AFC has multiple strong contenders',
      'Three-peat historically unprecedented',
    ],
    risks: [
      { description: 'Key player injury before/during playoffs', severity: 'HIGH', likelihood: 'MEDIUM' },
      { description: 'Single elimination format increases variance', severity: 'MEDIUM', likelihood: 'HIGH' },
    ],
    sources: [
      { title: 'ESPN NFL Analysis', url: 'https://espn.com', relevance: 'Sports analysis and odds' },
      { title: 'The Athletic', url: 'https://theathletic.com', relevance: 'In-depth team coverage' },
    ],
  },
  {
    event_ticker: 'KXGDP25Q1',
    market_ticker: 'KXGDP25Q1-2PCT',
    event_title: 'US GDP Growth Q1 2025',
    market_title: 'US GDP growth above 2% in Q1 2025?',
    category: 'Economics',
    current_yes_price: 61,
    yes_bid: 60,
    yes_ask: 62,
    volume_24h: 23450,
    open_interest: 67800,
    close_time: '2025-04-25T12:00:00Z',
    expiration_time: '2025-04-26T00:00:00Z',
    historicals: generateHistory(61, 7),
    sentiment_score: 0.28,
    analysis: 'Economic indicators suggest moderate growth continuing. Consumer spending remains solid, though business investment shows some softening.',
    predicted_outcome: 'YES',
    confidence: 65,
    summary: 'The US economy continues to show resilience with steady consumer spending and improving inflation. Q1 growth above 2% appears likely based on leading indicators.',
    tldr: 'US economy tracking for moderate growth above 2% in Q1.',
    key_takeaways: [
      'Consumer spending holding up',
      'Labor market still tight',
      'Business investment mixed',
      'Inflation headwinds easing',
    ],
    risks: [
      { description: 'Geopolitical shock disrupting trade', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Consumer pullback if layoffs increase', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Bureau of Economic Analysis', url: 'https://bea.gov', relevance: 'Official GDP data source' },
      { title: 'Atlanta Fed GDPNow', url: 'https://atlantafed.org', relevance: 'Real-time GDP tracking' },
    ],
  },
  {
    event_ticker: 'KXTSLA',
    market_ticker: 'KXTSLA-300',
    event_title: 'Tesla Stock Price',
    market_title: 'Tesla closes above $300 by Feb 2025?',
    category: 'Stocks',
    current_yes_price: 38,
    yes_bid: 37,
    yes_ask: 39,
    volume_24h: 78900,
    open_interest: 234500,
    close_time: '2025-02-28T21:00:00Z',
    expiration_time: '2025-03-01T00:00:00Z',
    historicals: generateHistory(38, 12),
    sentiment_score: -0.1,
    analysis: 'Tesla faces mixed sentiment with EV competition intensifying. While robotaxi promises excite investors, near-term fundamentals remain challenged.',
    predicted_outcome: 'NO',
    confidence: 58,
    summary: 'Tesla stock needs significant rally to reach $300. Competition in EVs is intensifying while Musk\'s attention is divided across ventures. Robotaxi launch timing remains uncertain.',
    tldr: 'Tesla $300 target faces headwinds from competition and execution.',
    key_takeaways: [
      'EV competition from Chinese makers',
      'Robotaxi timeline unclear',
      'Energy business growing steadily',
      'Valuation remains elevated vs peers',
    ],
    risks: [
      { description: 'Robotaxi regulatory approval accelerates', severity: 'MEDIUM', likelihood: 'LOW' },
      { description: 'Major product recall impacts sentiment', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Broader EV market slowdown', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Tesla Investor Relations', url: 'https://ir.tesla.com', relevance: 'Official company filings' },
      { title: 'Electrek', url: 'https://electrek.co', relevance: 'EV industry news' },
    ],
  },
  {
    event_ticker: 'KXOSCARS',
    market_ticker: 'KXOSCARS-BESTPIC',
    event_title: 'Academy Awards 2025',
    market_title: 'Anora wins Best Picture at 2025 Oscars?',
    category: 'Entertainment',
    current_yes_price: 52,
    yes_bid: 51,
    yes_ask: 53,
    volume_24h: 12340,
    open_interest: 45600,
    close_time: '2025-03-02T23:59:59Z',
    expiration_time: '2025-03-03T06:00:00Z',
    historicals: generateHistory(52, 10),
    sentiment_score: 0.4,
    analysis: 'Anora has strong momentum from festival circuit wins. However, Academy voters can be unpredictable and several strong contenders remain.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 55,
    summary: 'Anora emerged as a frontrunner after winning Palme d\'Or and strong critical reception. Academy voters tend to favor different criteria than festival juries, creating uncertainty.',
    tldr: 'Anora leads but Oscar race remains competitive.',
    key_takeaways: [
      'Won Palme d\'Or at Cannes',
      'Strong critical reviews',
      'Independent film faces studio competition',
      'Academy preferences can diverge from festivals',
    ],
    risks: [
      { description: 'Late-breaking controversy or scandal', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Strong late-season competitor emerges', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Variety Awards Coverage', url: 'https://variety.com', relevance: 'Industry awards tracking' },
      { title: 'Gold Derby', url: 'https://goldderby.com', relevance: 'Oscar predictions and analysis' },
    ],
  },
  {
    event_ticker: 'KXWEATHER',
    market_ticker: 'KXWEATHER-NYC-JAN',
    event_title: 'NYC Weather January 2025',
    market_title: 'NYC temperature below 10F in January 2025?',
    category: 'Climate',
    current_yes_price: 67,
    yes_bid: 66,
    yes_ask: 68,
    volume_24h: 8900,
    open_interest: 23400,
    close_time: '2025-01-31T23:59:59Z',
    expiration_time: '2025-02-01T00:00:00Z',
    historicals: generateHistory(67, 9),
    sentiment_score: 0.15,
    analysis: 'Historical data shows NYC typically experiences sub-10F temps in most Januaries. Current forecasts suggest cold air intrusions likely.',
    predicted_outcome: 'YES',
    confidence: 72,
    summary: 'January in NYC historically sees temperatures drop below 10F in most years. Arctic air masses frequently push into the Northeast during winter months.',
    tldr: 'Historical patterns favor sub-10F temps in NYC this January.',
    key_takeaways: [
      'Historical frequency around 70-80%',
      'Arctic oscillation patterns monitored',
      'La Nina conditions may influence',
      'Resolution based on Central Park data',
    ],
    risks: [
      { description: 'Unusually warm winter pattern persists', severity: 'LOW', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'NOAA Weather Data', url: 'https://noaa.gov', relevance: 'Official weather records' },
      { title: 'Weather Underground', url: 'https://wunderground.com', relevance: 'Historical weather data' },
    ],
  },
  {
    event_ticker: 'KXTECH',
    market_ticker: 'KXTECH-AAPL-AI',
    event_title: 'Apple AI Announcements',
    market_title: 'Apple announces major AI product by Q1 2025?',
    category: 'Tech',
    current_yes_price: 83,
    yes_bid: 82,
    yes_ask: 84,
    volume_24h: 34560,
    open_interest: 98700,
    close_time: '2025-03-31T23:59:59Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(83, 5),
    sentiment_score: 0.55,
    analysis: 'Apple Intelligence rollout continues with expanding features. The company has clearly committed to AI as a major focus area.',
    predicted_outcome: 'YES',
    confidence: 85,
    summary: 'Apple has already launched Apple Intelligence and continues expanding AI capabilities across devices. Further announcements are highly likely given their stated AI roadmap.',
    tldr: 'Apple AI announcements highly likely given ongoing rollout.',
    key_takeaways: [
      'Apple Intelligence already launched',
      'Siri improvements ongoing',
      'On-device AI differentiation',
      'Partnership with OpenAI active',
    ],
    risks: [
      { description: 'Delays in AI feature rollout', severity: 'LOW', likelihood: 'LOW' },
      { description: 'Definition of "major" is subjective', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Apple Newsroom', url: 'https://apple.com/newsroom', relevance: 'Official announcements' },
      { title: '9to5Mac', url: 'https://9to5mac.com', relevance: 'Apple news and rumors' },
    ],
  },
  {
    event_ticker: 'KXPOLITICS',
    market_ticker: 'KXPOLITICS-CABINET',
    event_title: 'Cabinet Confirmations',
    market_title: 'All cabinet nominees confirmed by Feb 2025?',
    category: 'Politics',
    current_yes_price: 34,
    yes_bid: 33,
    yes_ask: 35,
    volume_24h: 67800,
    open_interest: 234500,
    close_time: '2025-02-28T23:59:59Z',
    expiration_time: '2025-03-01T00:00:00Z',
    historicals: generateHistory(34, 8),
    sentiment_score: -0.25,
    analysis: 'Several controversial nominees face difficult confirmation battles. Senate process often extends beyond February for full cabinets.',
    predicted_outcome: 'NO',
    confidence: 68,
    summary: 'Cabinet confirmation processes historically extend into March or later. Several nominees face significant opposition that will slow the process.',
    tldr: 'Full cabinet confirmation by February unlikely given opposition.',
    key_takeaways: [
      'Several nominees face strong opposition',
      'Senate process deliberately slow',
      'Historical precedent favors delays',
      'Controversial picks require more debate',
    ],
    risks: [
      { description: 'Nominees withdrawn and replaced', severity: 'MEDIUM', likelihood: 'MEDIUM' },
      { description: 'Senate expedites process unexpectedly', severity: 'LOW', likelihood: 'LOW' },
    ],
    sources: [
      { title: 'Politico', url: 'https://politico.com', relevance: 'Political news coverage' },
      { title: 'Senate.gov', url: 'https://senate.gov', relevance: 'Official confirmation tracking' },
    ],
  },
  {
    event_ticker: 'KXSPACE',
    market_ticker: 'KXSPACE-STARSHIP',
    event_title: 'SpaceX Starship Milestones',
    market_title: 'Starship completes successful orbital flight by Q1 2025?',
    category: 'Space',
    current_yes_price: 56,
    yes_bid: 55,
    yes_ask: 57,
    volume_24h: 45670,
    open_interest: 156700,
    close_time: '2025-03-31T23:59:59Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(56, 11),
    sentiment_score: 0.3,
    analysis: 'SpaceX has made rapid progress but full orbital success with controlled landing remains challenging. Multiple test flights likely needed.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 55,
    summary: 'Starship development continues at rapid pace with each flight showing improvements. Full orbital success with recovery requires multiple systems working perfectly.',
    tldr: 'Starship progress promising but full success uncertain by Q1.',
    key_takeaways: [
      'Recent flights showed major improvements',
      'Chopstick catch successfully demonstrated',
      'FAA licensing can cause delays',
      'Multiple flights planned for Q1',
    ],
    risks: [
      { description: 'Flight anomaly causes lengthy investigation', severity: 'HIGH', likelihood: 'MEDIUM' },
      { description: 'Regulatory delays from FAA', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'SpaceX Updates', url: 'https://spacex.com', relevance: 'Official launch information' },
      { title: 'NASASpaceflight', url: 'https://nasaspaceflight.com', relevance: 'Space industry coverage' },
    ],
  },
  {
    event_ticker: 'KXOIL',
    market_ticker: 'KXOIL-80',
    event_title: 'Oil Price Q1 2025',
    market_title: 'Brent crude above $80/barrel average Q1 2025?',
    category: 'Commodities',
    current_yes_price: 48,
    yes_bid: 47,
    yes_ask: 49,
    volume_24h: 34560,
    open_interest: 123400,
    close_time: '2025-03-31T23:59:59Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(48, 10),
    sentiment_score: -0.05,
    analysis: 'Oil markets face crosswinds from OPEC+ cuts and weak demand growth. China economic recovery pace is key uncertainty.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 50,
    summary: 'Oil prices face competing forces: OPEC+ production cuts support prices while demand uncertainty from China weighs. Geopolitical risks add volatility.',
    tldr: 'Oil price outlook mixed with demand and supply uncertainties.',
    key_takeaways: [
      'OPEC+ maintaining production cuts',
      'China demand growth uncertain',
      'US production at record levels',
      'Geopolitical premium variable',
    ],
    risks: [
      { description: 'Major supply disruption from conflict', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Global recession crushes demand', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'OPEC+ discipline breaks down', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'EIA Petroleum Data', url: 'https://eia.gov', relevance: 'Official US energy data' },
      { title: 'Reuters Commodities', url: 'https://reuters.com', relevance: 'Commodities market news' },
    ],
  },
  {
    event_ticker: 'KXGAMING',
    market_ticker: 'KXGAMING-GTA6',
    event_title: 'GTA 6 Release',
    market_title: 'GTA 6 releases in 2025?',
    category: 'Gaming',
    current_yes_price: 71,
    yes_bid: 70,
    yes_ask: 72,
    volume_24h: 89000,
    open_interest: 345600,
    close_time: '2025-12-31T23:59:59Z',
    expiration_time: '2026-01-01T00:00:00Z',
    historicals: generateHistory(71, 8),
    sentiment_score: 0.35,
    analysis: 'Rockstar has confirmed Fall 2025 target. The company has strong track record on announced dates but delays are common in gaming.',
    predicted_outcome: 'YES',
    confidence: 72,
    summary: 'GTA 6 has an official Fall 2025 release window announced by Rockstar. While gaming delays are common, Rockstar typically delivers on announced dates.',
    tldr: 'GTA 6 on track for 2025 per Rockstar announcement.',
    key_takeaways: [
      'Official Fall 2025 release window',
      'Trailer generated massive hype',
      'Rockstar history of meeting dates',
      'Development appears on track',
    ],
    risks: [
      { description: 'Development delays push to 2026', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Quality issues force delay', severity: 'MEDIUM', likelihood: 'LOW' },
    ],
    sources: [
      { title: 'Rockstar Newswire', url: 'https://rockstargames.com', relevance: 'Official announcements' },
      { title: 'IGN', url: 'https://ign.com', relevance: 'Gaming industry coverage' },
    ],
  },
  {
    event_ticker: 'KXHEALTH',
    market_ticker: 'KXHEALTH-BIRD-FLU',
    event_title: 'Bird Flu Outbreak',
    market_title: 'US declares bird flu public health emergency by Q2 2025?',
    category: 'Health',
    current_yes_price: 23,
    yes_bid: 22,
    yes_ask: 24,
    volume_24h: 12340,
    open_interest: 45600,
    close_time: '2025-06-30T23:59:59Z',
    expiration_time: '2025-07-01T00:00:00Z',
    historicals: generateHistory(23, 7),
    sentiment_score: -0.3,
    analysis: 'While bird flu cases in livestock are spreading, human transmission remains limited. Health authorities are monitoring but emergency declaration threshold high.',
    predicted_outcome: 'NO',
    confidence: 74,
    summary: 'Bird flu H5N1 is spreading among dairy cattle with sporadic human cases. However, sustained human-to-human transmission needed for emergency declaration.',
    tldr: 'Bird flu concerning but emergency declaration unlikely without human spread.',
    key_takeaways: [
      'Cattle-to-human cases confirmed',
      'No sustained human transmission',
      'CDC monitoring closely',
      'Emergency threshold is high',
    ],
    risks: [
      { description: 'Virus mutates for human transmission', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Larger outbreak in farm workers', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'CDC H5N1 Updates', url: 'https://cdc.gov', relevance: 'Official health guidance' },
      { title: 'STAT News', url: 'https://statnews.com', relevance: 'Health industry coverage' },
    ],
  },
  {
    event_ticker: 'KXCRYPTO',
    market_ticker: 'KXCRYPTO-ETH-SPOT',
    event_title: 'Ethereum Spot ETF',
    market_title: 'Ethereum spot ETF AUM exceeds $10B by Q1 2025?',
    category: 'Crypto',
    current_yes_price: 41,
    yes_bid: 40,
    yes_ask: 42,
    volume_24h: 56780,
    open_interest: 189000,
    close_time: '2025-03-31T23:59:59Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(41, 12),
    sentiment_score: 0.1,
    analysis: 'Ethereum ETF flows have been modest compared to Bitcoin. Reaching $10B AUM requires significant acceleration in institutional interest.',
    predicted_outcome: 'NO',
    confidence: 62,
    summary: 'Ethereum spot ETFs launched with less fanfare than Bitcoin counterparts. Current pace of inflows suggests $10B AUM by Q1 2025 is challenging.',
    tldr: 'ETH ETF growth slower than BTC, $10B target ambitious.',
    key_takeaways: [
      'Launch flows below Bitcoin ETF',
      'Institutional interest more cautious',
      'Staking yield not available in ETF',
      'Competition from native staking',
    ],
    risks: [
      { description: 'ETH price rally accelerates inflows', severity: 'MEDIUM', likelihood: 'MEDIUM' },
      { description: 'Major institutional announcement', severity: 'MEDIUM', likelihood: 'LOW' },
    ],
    sources: [
      { title: 'Bloomberg ETF Analysis', url: 'https://bloomberg.com', relevance: 'ETF flow tracking' },
      { title: 'The Block', url: 'https://theblock.co', relevance: 'Crypto institutional news' },
    ],
  },
  {
    event_ticker: 'KXAUTO',
    market_ticker: 'KXAUTO-EV-SHARE',
    event_title: 'US EV Market Share',
    market_title: 'EVs exceed 10% of US car sales in Q1 2025?',
    category: 'Auto',
    current_yes_price: 76,
    yes_bid: 75,
    yes_ask: 77,
    volume_24h: 23450,
    open_interest: 67800,
    close_time: '2025-04-15T12:00:00Z',
    expiration_time: '2025-04-16T00:00:00Z',
    historicals: generateHistory(76, 6),
    sentiment_score: 0.4,
    analysis: 'EV adoption continues growing with expanded model availability. Q1 seasonal weakness could be offset by new model launches and incentives.',
    predicted_outcome: 'YES',
    confidence: 78,
    summary: 'US EV market share has been trending toward 10% with growing model availability and infrastructure. Q1 2025 crossing this threshold appears likely.',
    tldr: 'EV market share on track to exceed 10% in Q1 2025.',
    key_takeaways: [
      '2024 share approached 9%',
      'More affordable models launching',
      'Charging infrastructure expanding',
      'Q1 historically slower for car sales',
    ],
    risks: [
      { description: 'Incentive changes reduce demand', severity: 'MEDIUM', likelihood: 'LOW' },
      { description: 'Harsh winter reduces EV appeal', severity: 'LOW', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Cox Automotive', url: 'https://coxautoinc.com', relevance: 'Auto sales data' },
      { title: 'InsideEVs', url: 'https://insideevs.com', relevance: 'EV market tracking' },
    ],
  },
  {
    event_ticker: 'KXSPORTS',
    market_ticker: 'KXSPORTS-NBA-MVP',
    event_title: 'NBA MVP 2024-25',
    market_title: 'Nikola Jokic wins NBA MVP 2024-25?',
    category: 'Sports',
    current_yes_price: 44,
    yes_bid: 43,
    yes_ask: 45,
    volume_24h: 78900,
    open_interest: 234500,
    close_time: '2025-05-01T23:59:59Z',
    expiration_time: '2025-05-15T00:00:00Z',
    historicals: generateHistory(44, 9),
    sentiment_score: 0.2,
    analysis: 'Jokic continues elite play but voter fatigue and strong competition from Shai Gilgeous-Alexander and Luka Doncic create uncertainty.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 48,
    summary: 'Jokic seeks a fourth MVP but faces stiff competition. Voter fatigue after three wins may benefit other candidates with compelling narratives.',
    tldr: 'Jokic competitive but faces voter fatigue and strong rivals.',
    key_takeaways: [
      'Three-time MVP seeking fourth',
      'SGA and Luka strong candidates',
      'Team record matters for voting',
      'Voter fatigue historically significant',
    ],
    risks: [
      { description: 'Injury derails season', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Team struggles hurt candidacy', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'NBA.com', url: 'https://nba.com', relevance: 'Official league statistics' },
      { title: 'Basketball Reference', url: 'https://basketball-reference.com', relevance: 'Advanced statistics' },
    ],
  },
  {
    event_ticker: 'KXAI',
    market_ticker: 'KXAI-GPT5',
    event_title: 'OpenAI GPT-5 Release',
    market_title: 'OpenAI releases GPT-5 by Q2 2025?',
    category: 'AI',
    current_yes_price: 39,
    yes_bid: 38,
    yes_ask: 40,
    volume_24h: 123400,
    open_interest: 456700,
    close_time: '2025-06-30T23:59:59Z',
    expiration_time: '2025-07-01T00:00:00Z',
    historicals: generateHistory(39, 11),
    sentiment_score: 0.05,
    analysis: 'OpenAI has released o1 and other models but GPT-5 specifically remains unannounced. Company focus appears to be on reasoning models.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 45,
    summary: 'OpenAI\'s roadmap has shifted toward reasoning models like o1. Whether a model branded as "GPT-5" releases by Q2 2025 is uncertain.',
    tldr: 'GPT-5 timing unclear as OpenAI focuses on reasoning models.',
    key_takeaways: [
      'o1 model represents new direction',
      'GPT-5 not officially announced',
      'Competition pressure is high',
      'Naming/branding may change',
    ],
    risks: [
      { description: 'Model released under different name', severity: 'MEDIUM', likelihood: 'MEDIUM' },
      { description: 'Safety concerns delay release', severity: 'MEDIUM', likelihood: 'LOW' },
    ],
    sources: [
      { title: 'OpenAI Blog', url: 'https://openai.com/blog', relevance: 'Official announcements' },
      { title: 'The Information', url: 'https://theinformation.com', relevance: 'Tech industry reporting' },
    ],
  },
  {
    event_ticker: 'KXFINANCE',
    market_ticker: 'KXFINANCE-SP500',
    event_title: 'S&P 500 Q1 2025',
    market_title: 'S&P 500 closes above 6000 by end of Q1 2025?',
    category: 'Finance',
    current_yes_price: 58,
    yes_bid: 57,
    yes_ask: 59,
    volume_24h: 89000,
    open_interest: 345600,
    close_time: '2025-03-31T21:00:00Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(58, 8),
    sentiment_score: 0.25,
    analysis: 'Market momentum remains positive but stretched valuations and rate uncertainty create headwinds. Earnings growth key to sustaining rally.',
    predicted_outcome: 'UNCERTAIN',
    confidence: 55,
    summary: 'S&P 500 has rallied strongly but reaching 6000 requires continued momentum. Valuations are elevated and dependent on earnings growth materializing.',
    tldr: 'S&P 6000 possible but requires continued earnings growth.',
    key_takeaways: [
      'Strong 2024 performance to build on',
      'AI optimism supporting valuations',
      'Rate cut expectations supportive',
      'Valuations stretched vs history',
    ],
    risks: [
      { description: 'Earnings disappointments trigger selloff', severity: 'HIGH', likelihood: 'MEDIUM' },
      { description: 'Geopolitical shock hits risk assets', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'Inflation reaccelerates', severity: 'MEDIUM', likelihood: 'LOW' },
    ],
    sources: [
      { title: 'S&P Global', url: 'https://spglobal.com', relevance: 'Index provider' },
      { title: 'FactSet Earnings Insight', url: 'https://factset.com', relevance: 'Earnings analysis' },
    ],
  },
  {
    event_ticker: 'KXMEDIA',
    market_ticker: 'KXMEDIA-TIKTOK',
    event_title: 'TikTok US Status',
    market_title: 'TikTok still operational in US by end of Q1 2025?',
    category: 'Tech',
    current_yes_price: 62,
    yes_bid: 61,
    yes_ask: 63,
    volume_24h: 145600,
    open_interest: 567800,
    close_time: '2025-03-31T23:59:59Z',
    expiration_time: '2025-04-01T00:00:00Z',
    historicals: generateHistory(62, 13),
    sentiment_score: 0.1,
    analysis: 'Legal challenges and potential divestiture negotiations ongoing. Complete shutdown faces significant practical and political challenges.',
    predicted_outcome: 'YES',
    confidence: 65,
    summary: 'While TikTok faces regulatory pressure, complete shutdown involves complex legal and political considerations. Extension or workaround solutions likely.',
    tldr: 'TikTok likely to remain operational through Q1 despite pressure.',
    key_takeaways: [
      'Divestiture deadline approaching',
      'Legal challenges ongoing',
      'Political considerations complex',
      'Complete shutdown has precedent issues',
    ],
    risks: [
      { description: 'Court upholds immediate ban', severity: 'HIGH', likelihood: 'LOW' },
      { description: 'ByteDance refuses to divest', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Reuters Tech', url: 'https://reuters.com', relevance: 'Legal and regulatory news' },
      { title: 'TechCrunch', url: 'https://techcrunch.com', relevance: 'Tech industry coverage' },
    ],
  },
  {
    event_ticker: 'KXUKRAINE',
    market_ticker: 'KXUKRAINE-CEASEFIRE',
    event_title: 'Ukraine Conflict',
    market_title: 'Ukraine-Russia ceasefire announced by Q2 2025?',
    category: 'Geopolitics',
    current_yes_price: 31,
    yes_bid: 30,
    yes_ask: 32,
    volume_24h: 234500,
    open_interest: 890000,
    close_time: '2025-06-30T23:59:59Z',
    expiration_time: '2025-07-01T00:00:00Z',
    historicals: generateHistory(31, 9),
    sentiment_score: -0.2,
    analysis: 'Peace negotiations face fundamental obstacles on territorial and security issues. Both sides maintain maximalist positions publicly.',
    predicted_outcome: 'NO',
    confidence: 70,
    summary: 'While diplomatic efforts continue, fundamental disagreements on territory and security make a formal ceasefire by Q2 2025 unlikely.',
    tldr: 'Ceasefire unlikely given fundamental gaps in positions.',
    key_takeaways: [
      'Territorial disputes unresolved',
      'Security guarantee demands high',
      'Both sides dug in militarily',
      'New administration approach unclear',
    ],
    risks: [
      { description: 'Surprise diplomatic breakthrough', severity: 'MEDIUM', likelihood: 'LOW' },
      { description: 'Military situation forces negotiation', severity: 'MEDIUM', likelihood: 'MEDIUM' },
    ],
    sources: [
      { title: 'Institute for Study of War', url: 'https://understandingwar.org', relevance: 'Conflict analysis' },
      { title: 'Foreign Affairs', url: 'https://foreignaffairs.com', relevance: 'Geopolitical analysis' },
    ],
  },
];

// Get first N markets for different views
export function getMarketsForChart(count: number = 10): ProcessedEvent[] {
  return MOCK_MARKETS.slice(0, count);
}

export function getMarketsForList(count: number = 20): ProcessedEvent[] {
  return MOCK_MARKETS.slice(0, count);
}
